server {
    listen 80;
    
    # Compressão Gzip
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        
        # Fallback para o React Router
        try_files $uri $uri/ /index.html;
    }

    # Evita cache para o index.html (garante updates imediatos da SPA)
    location = /index.html {
        root /usr/share/nginx/html;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }
}
